version: 2

updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    day: friday
    interval: monthly
  groups:
    github-actions:
      patterns:
      - '*'

- package-ecosystem: composer
  directory: /
  schedule:
    day: friday
    interval: monthly
  groups:
    dependencies:
      patterns:
      - '*'

- package-ecosystem: docker
  directory: /
  schedule:
    day: friday
    interval: monthly
  groups:
    docker-images:
      patterns:
      - '*'
