version: 2

updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    day: friday
    interval: weekly

- package-ecosystem: composer
  directory: /
  schedule:
    day: friday
    interval: weekly
  groups:
    dependencies:
      patterns:
      - '*'

- package-ecosystem: docker
  directory: /
  schedule:
    day: friday
    interval: weekly
