version: '3.7'

services:
  php:
    image: ghcr.io/pararius/office-job-interview:latest
    environment:
      COMPOSER_CACHE_DIR: '/app/var/cache/composer'
    volumes:
    - ./:/app:delegated
    networks:
    - app

  pubsub:
    build:
      context: docker/emulator
      target: pubsub
    networks:
    - app

  firestore:
    build:
      context: docker/emulator
      target: firestore
    networks:
    - app

networks:
  app:
    name: app
