version: '3.7'

services:
  php:
    image: ghcr.io/pararius/office-job-interview:latest
    environment:
      COMPOSER_CACHE_DIR: '/app/var/cache/composer'
    volumes:
    - ./:/app:delegated
    networks:
    - app

  pubsub:
    image: eu.gcr.io/google.com/cloudsdktool/cloud-sdk:emulators
    command: ["gcloud", "beta", "emulators", "pubsub", "start", "--host-port=0.0.0.0:8081"]
    healthcheck:
      test: "curl --fail -s -o /dev/null localhost:8081"
      start_period: 20s
      interval: 2s
      timeout: 5s
      retries: 5
    networks:
    - app

  firestore:
    image: eu.gcr.io/google.com/cloudsdktool/cloud-sdk:emulators
    command: ["gcloud", "beta", "emulators", "firestore", "start", "--host-port=0.0.0.0:8081"]
    healthcheck:
      test: "curl --fail -s -o /dev/null localhost:8081"
      start_period: 20s
      interval: 2s
      timeout: 5s
      retries: 5
    networks:
    - app

networks:
  app:
    name: app
